openapi: "3.0.3"
info:
  title: "JSON API sample"
  description: "A JSON API that allows you to view and add customers"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:

components:
  schemas:
